import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "var(--inverse-primary)",
        "secondary": "var(--secondary)",
        "on-surface": "var(--on-surface)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-error-container": "var(--on-error-container)",
        "on-error": "var(--on-error)",
        "on-tertiary": "var(--on-tertiary)",
        "inverse-surface": "var(--inverse-surface)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "background": "var(--background)",
        "outline-variant": "var(--outline-variant)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "surface-container-high": "var(--surface-container-high)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-background": "var(--on-background)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-primary-container": "var(--on-primary-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "primary-container": "var(--primary-container)",
        "surface-bright": "var(--surface-bright)",
        "outline": "var(--outline)",
        "tertiary": "var(--tertiary)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "tertiary-container": "var(--tertiary-container)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-primary": "var(--on-primary)",
        "primary": "var(--primary)",
        "surface-container-highest": "var(--surface-container-highest)",
        "error": "var(--error)",
        "on-secondary-container": "var(--on-secondary-container)",
        "secondary-container": "var(--secondary-container)",
        "surface-tint": "var(--surface-tint)",
        "surface-container": "var(--surface-container)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "surface-container-low": "var(--surface-container-low)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "surface-dim": "var(--surface-dim)",
        "surface-variant": "var(--surface-variant)",
        "on-surface-variant": "var(--on-surface-variant)",
        "primary-fixed": "var(--primary-fixed)",
        "surface": "var(--surface)",
        "error-container": "var(--error-container)",
        "on-secondary": "var(--on-secondary)"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "margin": "32px",
        "unit": "4px",
        "lg": "24px",
        "max_width": "1440px",
        "gutter": "20px",
        "xl": "48px",
        "xs": "4px",
        "md": "16px"
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "h1": ["Inter"],
        "body-lg": ["Inter"],
        "h3": ["Inter"],
        "h2": ["Inter"],
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "h1": ["36px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "h3": ["20px", { "lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600" }],
        "h2": ["28px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};

export default config;